name: SkHttp
version: '@version@'
main: lol.aabss.skhttp.SkHttp
api-version: '1.13'
depend: [Skript]
softdepend: [SkJson]
authors: [aabss]
description: Http client, http server, websockets and discord webhooks for Skript. Requires Skript 2.15+.
commands:
  skhttp:
    permission: skhttp.command